import { useState, useEffect, useRef, useMemo } from 'react';
import { generateTwoWayTrades, generateThreeWayTrades, generateInverseTrades, applyTeamMode } from '../tradeAlgorithm';
import './TradeMachine.css';

const MODES = ['contender', 'neutral', 'rebuilder'];
const API_BASE = import.meta.env.PROD ? '' : (import.meta.env.VITE_API_BASE || 'http://localhost:5000');

const PosBadge = ({ pos }) => pos ? <span className={`pos-badge pos-${pos}`}>{pos === 'RDP' ? 'PK' : pos}</span> : null;

const TARGET_TIERS = [
  { key: 'any',     label: 'Any',                 min: 0,    max: Infinity },
  { key: 'elite',   label: 'Elite (5K+)',         min: 5000, max: Infinity },
  { key: 'starter', label: 'Starter (2.5K–5K)',   min: 2500, max: 5000 },
  { key: 'depth',   label: 'Depth (1K–2.5K)',     min: 1000, max: 2500 },
  { key: 'flier',   label: 'Flier (<1K)',         min: 1,    max: 1000 },
];

export default function TradeMachine() {
  const [leagues, setLeagues] = useState([]);
  const [config, setConfig] = useState(null);
  const [selectedLeagueId, setSelectedLeagueId] = useState('');
  
  const [isThreeWay, setIsThreeWay] = useState(false);
  const [rankingsMaps, setRankingsMaps] = useState({ dynasty: new Map(), redraft: new Map() });
  const [rankingsFormat, setRankingsFormat] = useState('dynasty'); // auto-set from league type, user-overridable
  const rankingsMap = rankingsMaps[rankingsFormat];
  const [rosterData, setRosterData] = useState([]); // List of team objects
  const [isLoadingLeague, setIsLoadingLeague] = useState(false);
  
  // Selected teams for the trade panels (Team A, Team B, Team C)
  const [teamA, setTeamA] = useState('');
  const [teamB, setTeamB] = useState('');
  const [teamC, setTeamC] = useState('');

  // Roster modes
  const [modeA, setModeA] = useState('neutral');
  const [modeB, setModeB] = useState('neutral');
  const [modeC, setModeC] = useState('neutral');

  // Trade Assets (Array of { id, originalOwner, dest })
  const [assetsA, setAssetsA] = useState([]);
  const [assetsB, setAssetsB] = useState([]);
  const [assetsC, setAssetsC] = useState([]);

  // Trade Finder State
  const [searchMode, setSearchMode] = useState('shop'); // 'shop' or 'acquire'
  const [tradeBlock, setTradeBlock] = useState([]);
  const [targetNeeds, setTargetNeeds] = useState([]);
  const [targetTier, setTargetTier] = useState('any'); // acquire mode: value band for targets
  const [finderResults, setFinderResults] = useState([]);
  const [isFinding, setIsFinding] = useState(false);
  const [hasSearched, setHasSearched] = useState(false);
  
  // Evaluation Result
  const [evaluation, setEvaluation] = useState(null);
  const [isEvaluating, setIsEvaluating] = useState(false);

  // Sleeper Sync
  const [sleeperUsername, setSleeperUsername] = useState('');
  const [isSyncingLeagues, setIsSyncingLeagues] = useState(false);
  const [syncError, setSyncError] = useState('');

  // Derived user team
  const activeLeague = leagues.find(l => String(l.sleeper_league_id) === String(selectedLeagueId));
  let userManagerName = activeLeague?.user_team_username || config?.user_team_username || sleeperUsername || '';
  if (!userManagerName && rosterData.length > 0) userManagerName = rosterData[0].name;
  const userTeam = rosterData.find(t => t.name === userManagerName) || rosterData[0];

  // 1. Initial Load: Configs & Rankings
  useEffect(() => {
    async function init() {
      try {
        // Fetch configs generated by background script
        const [lgRes, cfgRes, rankRes, redraftRes] = await Promise.all([
          fetch('/leagues.json').catch(() => null),
          fetch('/config.json').catch(() => null),
          fetch(`${API_BASE}/api/rankings`).catch(() => null),
          fetch(`${API_BASE}/api/rankings?format=redraft`).catch(() => null)
        ]);

        if (lgRes && lgRes.ok) setLeagues(await lgRes.json());
        if (cfgRes && cfgRes.ok) setConfig(await cfgRes.json());

        const buildMap = (rList) => {
          const rMap = new Map();
          rList.forEach(p => {
            if (p.sleeper_id) rMap.set(p.sleeper_id, p);
            // Also map by name and KTC ID for draft picks
            rMap.set(p.name, p);
            rMap.set(p.id, p);
          });
          return rMap;
        };

        const maps = { dynasty: new Map(), redraft: new Map() };
        if (rankRes && rankRes.ok) maps.dynasty = buildMap(await rankRes.json());
        if (redraftRes && redraftRes.ok) maps.redraft = buildMap(await redraftRes.json());
        setRankingsMaps(maps);
      } catch (err) {
        console.error("Initialization error:", err);
      }
    }
    init();
  }, []);

  // 1b. Auto-detect league type → rankings format (Sleeper settings.type: 0=redraft, 1=keeper, 2=dynasty)
  useEffect(() => {
    if (!selectedLeagueId) return;
    let cancelled = false;
    fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}`)
      .then(r => r.json())
      .then(l => {
        if (cancelled || !l || l.settings?.type == null) return;
        setRankingsFormat(l.settings.type === 2 ? 'dynasty' : 'redraft');
      })
      .catch(() => {});
    return () => { cancelled = true; };
  }, [selectedLeagueId]);

  // 2. Load Sleeper League Rosters
  useEffect(() => {
    if (!selectedLeagueId) return;

    async function fetchLeague() {
      setIsLoadingLeague(true);
      try {
        const [uRes, rRes, pRes, dRes] = await Promise.all([
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/users`),
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/rosters`),
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/traded_picks`),
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/drafts`).catch(() => null)
        ]);

        const users = await uRes.json();
        const rosters = await rRes.json();
        const tradedPicks = await pRes.json();
        const drafts = dRes && dRes.ok ? await dRes.json() : [];

        // A season whose draft already ran has no rookie picks left to trade
        const completedSeasons = new Set(
          (Array.isArray(drafts) ? drafts : [])
            .filter(d => d.status === 'complete')
            .map(d => parseInt(d.season))
        );

        const allPicks = [];
        const curYear = new Date().getFullYear();
        // Redraft/keeper leagues trade players, not future rookie picks
        const seasons = rankingsFormat === 'redraft'
          ? []
          : [curYear, curYear + 1, curYear + 2, curYear + 3].filter(s => !completedSeasons.has(s));
        const rounds = [1, 2, 3, 4];
        
        rosters.forEach(r => {
           seasons.forEach(season => {
             rounds.forEach(round => {
                allPicks.push({
                   season,
                   round,
                   original_owner_id: r.roster_id,
                   owner_id: r.roster_id 
                });
             });
           });
        });

        tradedPicks.forEach(tp => {
             const pick = allPicks.find(p => p.season === parseInt(tp.season) && p.round === tp.round && p.original_owner_id === tp.roster_id);
             if (pick) {
                 pick.owner_id = tp.owner_id;
             }
        });
        
        const formatted = rosters.map(r => {
          const user = users.find(u => u.user_id === r.owner_id);
          const name = user?.display_name || `Team ${r.roster_id}`;
          
          // Group players by position
          const players = { QB: [], RB: [], WR: [], TE: [], Picks: [] };
          if (r.players) {
            r.players.forEach(pid => {
              const p = rankingsMap.get(pid);
              if (p && players[p.position]) {
                players[p.position].push(p);
              }
            });
          }

          const teamPicks = allPicks.filter(p => p.owner_id === r.roster_id);
          teamPicks.forEach(pick => {
             const suffix = pick.round === 1 ? '1st' : pick.round === 2 ? '2nd' : pick.round === 3 ? '3rd' : '4th';
             const pickName = `${pick.season} Mid ${suffix}`;
             let pickData = rankingsMap.get(pickName);
             
             // Fallback for far-future picks not yet in KTC database
             if (!pickData && pick.season > curYear + 2) {
                 const baseVals = { 1: 3000, 2: 1000, 3: 300, 4: 100 };
                 pickData = {
                     id: `mock_${pick.season}_${suffix}`,
                     name: pickName,
                     position: 'RDP',
                     composite_value: baseVals[pick.round] || 100,
                     ktc_value: baseVals[pick.round] || 100,
                     ecr_value: baseVals[pick.round] || 100
                 };
             }
             
             const origRoster = rosters.find(or => or.roster_id === pick.original_owner_id);
             const origUser = users.find(u => u.user_id === origRoster?.owner_id);
             const origName = origUser?.display_name || `Team ${pick.original_owner_id}`;
             
             if (pickData) {
                 players.Picks.push({
                     ...pickData,
                     id: `${pickName}_${pick.original_owner_id}`.replace(/\s+/g, '_'),
                     eval_id: pickData.id,
                     name: `${pick.season} ${suffix} (${origName})`
                 });
             }
          });

          // Sort each position group
          Object.keys(players).forEach(pos => {
            players[pos].sort((a, b) => b.composite_value - a.composite_value);
          });

          return { roster_id: r.roster_id, name, players };
        });

        setRosterData(formatted);
        // Reset selections
        setTeamA(''); setTeamB(''); setTeamC('');
        setAssetsA([]); setAssetsB([]); setAssetsC([]);
        setEvaluation(null);
        // Reset finder state — selections from another league are meaningless here
        setTradeBlock([]); setTargetNeeds([]);
        setFinderResults([]); setHasSearched(false);
      } catch (err) {
        console.error("Failed to load Sleeper data", err);
      } finally {
        setIsLoadingLeague(false);
      }
    }
    fetchLeague();
  }, [selectedLeagueId, rankingsMap]);

  // 3. Sleeper Sync Logic
  const handleSyncSleeper = async () => {
    if (!sleeperUsername) return;
    setIsSyncingLeagues(true);
    setSyncError('');
    try {
      // 1. Get user_id from username
      const userRes = await fetch(`https://api.sleeper.app/v1/user/${sleeperUsername.trim()}`);
      const userData = await userRes.json();
      if (!userData || !userData.user_id) throw new Error(`No Sleeper user named "${sleeperUsername.trim()}"`);

      const actualUsername = userData.display_name || sleeperUsername;

      // 2. Get leagues for the current season, falling back to last season (offseason edge case)
      const year = new Date().getFullYear();
      let lgData = null;
      for (const y of [year, year - 1]) {
        const lgRes = await fetch(`https://api.sleeper.app/v1/user/${userData.user_id}/leagues/nfl/${y}`);
        lgData = await lgRes.json();
        if (Array.isArray(lgData) && lgData.length > 0) break;
      }

      if (Array.isArray(lgData) && lgData.length > 0) {
        const mapped = lgData.map(l => ({
          name: l.name,
          sleeper_league_id: l.league_id,
          user_team_username: actualUsername
        }));
        setLeagues(mapped);
        setSelectedLeagueId(mapped[0].sleeper_league_id);
      } else {
        setSyncError(`No leagues found for ${actualUsername}`);
      }
    } catch (e) {
      console.error("Failed to sync sleeper", e);
      setSyncError(e.message || 'Sync failed — check the username and try again.');
    } finally {
      setIsSyncingLeagues(false);
    }
  };

  // 4. Trade Finder Logic
  const handleFindTrades = async (type = '2-way') => {
    setIsFinding(true);
    setFinderResults([]);
    setHasSearched(true);
    
    // allow UI to render spinner
    await new Promise(r => setTimeout(r, 50)); 
    
    try {
      const activeLeague = leagues.find(l => String(l.sleeper_league_id) === String(selectedLeagueId));
      let userManagerName = activeLeague?.user_team_username || config?.user_team_username || '';
      if (!userManagerName && rosterData.length > 0) userManagerName = rosterData[0].name;
      const userTeam = rosterData.find(t => t.name === userManagerName) || rosterData[0];

      let results = [];
      if (searchMode === 'acquire') {
         const tier = TARGET_TIERS.find(t => t.key === targetTier) || TARGET_TIERS[0];
         results = generateInverseTrades({
           rosterData,
           userTeamId: userTeam.roster_id,
           targetNeeds,
           userMode: 'neutral',
           minTargetValue: tier.min,
           maxTargetValue: tier.max
         });
      } else if (type === '2-way') {
         results = generateTwoWayTrades({
           rosterData, 
           userTeamId: userTeam.roster_id, 
           userAssets: tradeBlock, 
           targetNeeds 
         });
      } else {
         results = generateThreeWayTrades({
           rosterData, 
           userTeamId: userTeam.roster_id, 
           userAssets: tradeBlock, 
           targetNeeds 
         });
      }
      setFinderResults(results);
    } catch (e) {
      console.error("Algorithm error:", e);
    } finally {
      setIsFinding(false);
    }
  };

  const applyFinderTrade = (tradeObj) => {
    if (!tradeObj) return;

    // Determine the user
    const activeLeague = leagues.find(l => String(l.sleeper_league_id) === String(selectedLeagueId));
    let userManagerName = activeLeague?.user_team_username || config?.user_team_username || '';
    if (!userManagerName && rosterData.length > 0) userManagerName = rosterData[0].name;
    const userTeam = rosterData.find(t => t.name === userManagerName) || rosterData[0];

    const tA = userTeam;
    const tB = rosterData.find(t => String(t.roster_id) === String(tradeObj.teamB_id));
    const tC = tradeObj.type === '3-way' ? rosterData.find(t => String(t.roster_id) === String(tradeObj.teamC_id)) : null;

    setTeamA(String(tA.roster_id));
    setTeamB(String(tB.roster_id));
    if (tC) {
      setIsThreeWay(true);
      setTeamC(String(tC.roster_id));
    } else {
      setIsThreeWay(false);
      setTeamC('');
    }

    if (tradeObj.type === '2-way') {
      const aSent = tradeObj.assetsSent.map(a => ({ ...a, destId: String(tB.roster_id) }));
      const bSent = tradeObj.assetsReceived.map(a => ({ ...a, destId: String(tA.roster_id) }));
      setAssetsA(aSent);
      setAssetsB(bSent);
      setAssetsC([]);
      calculateTrade(aSent, bSent, [], false, String(tA.roster_id), String(tB.roster_id), '');
    } else {
      const aSent = [
        ...tradeObj.assetsSentToB.map(a => ({ ...a, destId: String(tB.roster_id) })),
        ...tradeObj.assetsSentToC.map(a => ({ ...a, destId: String(tC.roster_id) }))
      ];
      const bSent = tradeObj.assetsReceivedFromB.map(a => ({ ...a, destId: String(tA.roster_id) }));
      const cSent = tradeObj.assetsReceivedFromC.map(a => ({ ...a, destId: String(tA.roster_id) }));

      // Broker asset travels between the two opponents
      if (tradeObj.broker) {
        const brokered = { ...tradeObj.broker.asset, destId: String(tradeObj.broker.toId) };
        if (String(tradeObj.broker.fromId) === String(tB.roster_id)) bSent.push(brokered);
        else cSent.push(brokered);
      }

      setAssetsA(aSent);
      setAssetsB(bSent);
      setAssetsC(cSent);
      calculateTrade(aSent, bSent, cSent, true, String(tA.roster_id), String(tB.roster_id), String(tC.roster_id));
    }
  };

  const balanceSuggestion = useMemo(() => {
    if (!evaluation || !teamA || !teamB) return null;
    
    if (evaluation.isThreeWay) {
      if (!teamC) return null;
      
      const nets = [
        { id: teamA, net: evaluation.netA || 0 },
        { id: teamB, net: evaluation.netB || 0 },
        { id: teamC, net: evaluation.netC || 0 }
      ];
      
      // Sort by net descending (biggest winner first, biggest loser last)
      nets.sort((a, b) => b.net - a.net);
      const winner = nets[0];
      const loser = nets[2];
      
      // If the difference between winner and loser is minor, it's balanced
      if (winner.net - loser.net < 50) return null;
      if (winner.net <= 0 || loser.net >= 0) return null; // Edge case safety
      
      const targetValue = Math.min(winner.net, Math.abs(loser.net));
      
      const winningRoster = rosterData.find(t => String(t.roster_id) === String(winner.id));
      if (!winningRoster) return null;
      
      const winningAssets = winner.id === teamA ? assetsA : winner.id === teamB ? assetsB : assetsC;
      
      const candidatePlayers = [
        ...winningRoster.players.QB,
        ...winningRoster.players.RB,
        ...winningRoster.players.WR,
        ...winningRoster.players.TE,
        ...winningRoster.players.Picks
      ].filter(p => !winningAssets.some(a => a.id === p.id));
      
      let bestPlayer = null;
      let minDiff = Infinity;
      
      candidatePlayers.forEach(p => {
        const d = Math.abs(p.composite_value - targetValue);
        if (d < minDiff) {
          minDiff = d;
          bestPlayer = p;
        }
      });
      
      if (bestPlayer && bestPlayer.composite_value > 0) {
        return {
          player: bestPlayer,
          sourceTeamId: winner.id,
          destTeamId: loser.id,
          sourceTeamName: winningRoster.name,
          targetTeamName: rosterData.find(t => String(t.roster_id) === String(loser.id))?.name || 'the other side'
        };
      }
      return null;
    }

    const valA = evaluation.final_sideA_total || 0;
    const valB = evaluation.final_sideB_total || 0;
    const diff = Math.abs(valA - valB);
    
    // If the difference is minor (less than 50), the trade is already perfectly balanced
    if (diff < 50) return null;

    // If valA > valB: Side A total sent is greater than Side B total sent.
    // That means Side A is sending more value. Side B is winning.
    // To balance: Side B needs to add a player to send to Side A.
    // If valB > valA: Side B is sending more value. Side A is winning.
    // To balance: Side A needs to add a player to send to Side B.
    const winningId = valA > valB ? teamB : teamA; // The team receiving more value (gets more, sends less)
    const losingId = valA > valB ? teamA : teamB;  // The team receiving less value (sends more, gets less)
    
    const winningRoster = rosterData.find(t => String(t.roster_id) === String(winningId));
    if (!winningRoster) return null;
    
    const winningAssets = winningId === teamA ? assetsA : winningId === teamB ? assetsB : assetsC;
    
    // Gather all players on the winning manager's roster not currently in the trade
    const candidatePlayers = [
      ...winningRoster.players.QB,
      ...winningRoster.players.RB,
      ...winningRoster.players.WR,
      ...winningRoster.players.TE,
      ...winningRoster.players.Picks
    ].filter(p => !winningAssets.some(a => a.id === p.id));
    
    // Find the player whose value is closest to the difference
    let bestPlayer = null;
    let minDiff = Infinity;
    
    candidatePlayers.forEach(p => {
      const d = Math.abs(p.composite_value - diff);
      if (d < minDiff) {
        minDiff = d;
        bestPlayer = p;
      }
    });
    
    if (bestPlayer && bestPlayer.composite_value > 0) {
      return {
        player: bestPlayer,
        sourceTeamId: winningId,
        destTeamId: losingId,
        sourceTeamName: winningRoster.name,
        targetTeamName: rosterData.find(t => String(t.roster_id) === String(losingId))?.name || 'the other side'
      };
    }
    
    return null;
  }, [evaluation, teamA, teamB, teamC, assetsA, assetsB, assetsC, rosterData]);

  const applyBalance = () => {
    if (!balanceSuggestion) return;
    const { sourceTeamId, player, destTeamId } = balanceSuggestion;
    
    const listMap = { [teamA]: setAssetsA, [teamB]: setAssetsB, [teamC]: setAssetsC };
    const curMap = { [teamA]: assetsA, [teamB]: assetsB, [teamC]: assetsC };
    
    const curList = curMap[sourceTeamId];
    const setList = listMap[sourceTeamId];
    if (setList) {
      const updatedAsset = { ...player, destId: destTeamId };
      const updatedList = [...curList, updatedAsset];
      setList(updatedList);
      
      const nextA = sourceTeamId === teamA ? updatedList : assetsA;
      const nextB = sourceTeamId === teamB ? updatedList : assetsB;
      const nextC = sourceTeamId === teamC ? updatedList : assetsC;
      
      calculateTrade(nextA, nextB, nextC, isThreeWay, teamA, teamB, teamC);
    }
  };

  // 4. Trade Asset Selection & Evaluation
  const toggleAsset = (teamId, asset, destId) => {
    const listMap = { [teamA]: setAssetsA, [teamB]: setAssetsB, [teamC]: setAssetsC };
    const curMap = { [teamA]: assetsA, [teamB]: assetsB, [teamC]: assetsC };
    
    const curList = curMap[teamId];
    const setList = listMap[teamId];
    if (!setList) return;

    if (curList.find(a => a.id === asset.id)) {
      setList(curList.filter(a => a.id !== asset.id));
    } else {
      setList([...curList, { ...asset, destId }]);
    }
  };

  const calculateTrade = async (
    overrideA,
    overrideB,
    overrideC,
    forceThreeWay,
    overrideTeamA,
    overrideTeamB,
    overrideTeamC
  ) => {
    const finalA = overrideA || assetsA;
    const finalB = overrideB || assetsB;
    const finalC = overrideC || assetsC;
    const finalThreeWay = forceThreeWay !== undefined ? forceThreeWay : isThreeWay;
    const finalTeamA = overrideTeamA || teamA;
    const finalTeamB = overrideTeamB || teamB;
    const finalTeamC = overrideTeamC || teamC;

    setIsEvaluating(true);
    try {
      if (!finalThreeWay) {
        // Standard 2-way call to evaluator
        const res = await fetch(`${API_BASE}/api/evaluate`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            sideA: { players: finalA.map(a => a.eval_id || a.id), picks: [] },
            sideB: { players: finalB.map(a => a.eval_id || a.id), picks: [] },
            settings: { team_1_mode: modeA, team_2_mode: modeB, format: rankingsFormat }
          })
        });
        const data = await res.json();
        setEvaluation({ ...data, isThreeWay: false });
        // Auto-scroll to results on mobile
        setTimeout(() => {
          const resultsEl = document.querySelector('.results-panel');
          if (resultsEl) resultsEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }, 100);
      } else {
        // 3-way offline calculation — same age/position model as the 2-way evaluator
        const getAdjusted = (asset, mode) => applyTeamMode(asset.composite_value, asset.position, asset.age, mode);

        const calcNet = (teamId, list, mode) => {
          let sentValue = 0;
          let receivedValue = 0;
          
          // Assets sent away by teamId
          list.forEach(a => {
            if (a.destId !== teamId) sentValue += getAdjusted(a, mode);
          });
          
          // Assets received by teamId
          [finalA, finalB, finalC].forEach(otherList => {
            otherList.forEach(a => {
              if (a.destId === teamId) receivedValue += getAdjusted(a, mode);
            });
          });
          return receivedValue - sentValue;
        };

        const netA = calcNet(finalTeamA, finalA, modeA);
        const netB = calcNet(finalTeamB, finalB, modeB);
        const netC = calcNet(finalTeamC, finalC, modeC);
        
        setEvaluation({ isThreeWay: true, netA, netB, netC });
        // Auto-scroll to results on mobile
        setTimeout(() => {
          const resultsEl = document.querySelector('.results-panel');
          if (resultsEl) resultsEl.scrollIntoView({ behavior: 'smooth', block: 'nearest' });
        }, 100);
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsEvaluating(false);
    }
  };

  const renderRoster = (teamId, currentDest) => {
    const team = rosterData.find(t => String(t.roster_id) === String(teamId));
    if (!team) return <div style={{opacity:0.5, padding:'1rem'}}>Select a team</div>;
    
    // which assets has this team already added?
    const teamAssets = teamId === teamA ? assetsA : teamId === teamB ? assetsB : assetsC;

    return (
      <div className="roster-picker">
        {['QB', 'RB', 'WR', 'TE', 'Picks'].map(pos => {
          const players = team.players[pos];
          if (!players || players.length === 0) return null;
          return (
            <div key={pos} className="roster-group">
              <div className="roster-group-title">{pos}</div>
              {players.map(p => {
                const isSelected = teamAssets.find(a => a.id === p.id);
                return (
                  <div 
                    key={p.id} 
                    className={`roster-player ${isSelected ? 'selected' : ''}`}
                    onClick={() => toggleAsset(teamId, p, currentDest)}
                  >
                    <span>{p.name}</span>
                    <span style={{color: '#888'}}>{p.composite_value}</span>
                  </div>
                );
              })}
            </div>
          )
        })}
      </div>
    );
  };

  const renderPanel = (sideLabel, teamState, setTeam, modeState, setMode, destState, setDest, assetsList) => (
    <div className="team-panel glass-panel">
      <div className="team-header">
        <h3>{sideLabel}</h3>
        <select className="team-select" value={teamState} onChange={e => setTeam(e.target.value)}>
          <option value="">-- Select Team --</option>
          {rosterData.map(t => <option key={t.roster_id} value={t.roster_id}>{t.name}</option>)}
        </select>
      </div>
      
      <div className="mode-pills">
        {MODES.map(m => (
          <button key={m} className={`mode-pill ${modeState === m ? `active ${m}` : ''}`} onClick={() => setMode(m)}>
            {m}
          </button>
        ))}
      </div>

      <div className="assets-box" style={{marginTop:'1rem'}}>
        <div className="roster-group-title">Assets Sent</div>
        {assetsList.length === 0 && <div style={{opacity:0.5, fontSize:'0.9rem', padding:'0.5rem'}}>No assets selected</div>}
        {assetsList.map(a => (
          <div key={a.id} className="asset-item">
            <div className="asset-info">
              <span className="asset-name"><PosBadge pos={a.position}/>{a.name}</span>
              <span className="asset-dest">
                To: {rosterData.find(t=>String(t.roster_id)===String(a.destId))?.name || 'Unknown'}
              </span>
            </div>
            <div className="asset-actions">
              <button onClick={() => toggleAsset(teamState, a, a.destId)}>✖</button>
            </div>
          </div>
        ))}
      </div>

      {teamState && (
        <div style={{marginTop:'1rem'}}>
          {/* In a 2-way trade the destination is always the other side — only ask in 3-way */}
          {isThreeWay && (
            <div style={{display:'flex', gap:'0.5rem', marginBottom:'0.5rem'}}>
              <span className="roster-group-title" style={{border:'none', margin:0}}>Send to:</span>
              <select style={{background:'rgba(0,0,0,0.5)', color:'white', border:'1px solid #555', borderRadius:'4px'}} value={destState} onChange={e => setDest(e.target.value)}>
                <option value="">Select Dest</option>
                {teamState !== teamA && teamA && <option value={teamA}>Side A</option>}
                {teamState !== teamB && teamB && <option value={teamB}>Side B</option>}
                {teamState !== teamC && teamC && <option value={teamC}>Side C</option>}
              </select>
            </div>
          )}
          {renderRoster(teamState, isThreeWay ? destState : (String(teamState) === String(teamA) ? teamB : teamA))}
        </div>
      )}
    </div>
  );

  // Default dests
  const [destA, setDestA] = useState('');
  const [destB, setDestB] = useState('');
  const [destC, setDestC] = useState('');

  useEffect(() => {
    if (teamB && !destA) setDestA(teamB);
  }, [teamB, destA]);

  useEffect(() => {
    if (teamA && !destB) setDestB(teamA);
  }, [teamA, destB]);

  useEffect(() => { if (!destC) setDestC(teamA); }, [teamA]);

  return (
    <div className="trade-machine-wrapper">
      
      {/* Top Controls */}
      <div className="glass-panel trade-controls">
        <div className="league-selector" style={{flex: 1, display: 'flex', alignItems: 'center', flexWrap: 'wrap', gap: '1rem'}}>
          <div className="sync-box">
             <span className="sync-label">Sleeper Username:</span>
             <input
               type="text"
               className="sync-input"
               placeholder="e.g. Rhymenoceros"
               value={sleeperUsername}
               onChange={e => setSleeperUsername(e.target.value)}
               onKeyDown={e => { if (e.key === 'Enter' && sleeperUsername && !isSyncingLeagues) handleSyncSleeper(); }}
             />
             <button
               className="sync-btn"
               onClick={handleSyncSleeper}
               disabled={isSyncingLeagues || !sleeperUsername}
             >
               {isSyncingLeagues ? 'Syncing...' : 'Sync'}
             </button>
          </div>
          {syncError && <span className="sync-error">⚠ {syncError}</span>}

          <select value={selectedLeagueId} onChange={(e) => setSelectedLeagueId(e.target.value)}>
            <option value="">-- Select League --</option>
            {leagues.map(l => (
              <option key={l.sleeper_league_id} value={l.sleeper_league_id}>{l.name}</option>
            ))}
          </select>
          <div className="trade-type-toggle" style={{fontSize:'0.85rem'}}>
            <button className={rankingsFormat === 'dynasty' ? 'active' : ''} onClick={() => setRankingsFormat('dynasty')}>💎 Dynasty</button>
            <button className={rankingsFormat === 'redraft' ? 'active' : ''} onClick={() => setRankingsFormat('redraft')}>🔁 Redraft</button>
          </div>

          {isLoadingLeague && <span style={{color: '#00ff88', fontSize:'0.9rem'}}>Loading rosters...</span>}
        </div>

        <div className="trade-type-toggle">
          <button className={!isThreeWay ? 'active' : ''} onClick={() => {setIsThreeWay(false); setTeamC(''); setAssetsC([]);}}>2-Way Trade</button>
          <button className={isThreeWay ? 'active' : ''} onClick={() => setIsThreeWay(true)}>3-Way Trade</button>
        </div>
      </div>

      {/* Algorithmic Trade Finder */}
      <div className="glass-panel ai-assistant-container">
        <div className="finder-header">
           <h3 style={{marginTop:0, marginBottom:0, color:'#00ccff', display:'flex', alignItems:'center', gap:'0.5rem'}}>
             ⚡ Algorithmic Trade Finder
           </h3>
           <div className="trade-type-toggle" style={{fontSize:'0.85rem'}}>
              <button className={searchMode === 'shop' ? 'active' : ''} onClick={() => {setSearchMode('shop'); setTargetNeeds([]); setFinderResults([]); setHasSearched(false);}}>🛒 Shop My Players</button>
              <button className={searchMode === 'acquire' ? 'active' : ''} onClick={() => {setSearchMode('acquire'); setTradeBlock([]); setFinderResults([]); setHasSearched(false);}}>🎯 Acquire a Position</button>
           </div>
        </div>
        
        <div style={{display:'flex', flexWrap:'wrap', gap:'2rem', marginBottom:'1.5rem'}}>
           {/* Trading Block Selection (Only in Shop mode) */}
           {searchMode === 'shop' && (
             <div style={{flex: 1, minWidth: '300px'}}>
                <div className="roster-group-title"><span className="step-num">1</span>Select Assets to Trade Away</div>
                {userTeam && (
                  <div className="roster-picker" style={{maxHeight:'250px', background:'rgba(0,0,0,0.2)', border:'1px solid rgba(255,255,255,0.05)', borderRadius:'8px', padding:'0.5rem'}}>
                    {['QB', 'RB', 'WR', 'TE', 'Picks'].map(pos => {
                      const players = userTeam.players[pos];
                      if (!players || players.length === 0) return null;
                      return (
                        <div key={pos} className="roster-group">
                          <div className="roster-group-title" style={{fontSize:'0.85rem', color:'#888', paddingBottom:'0.2rem'}}>{pos}</div>
                          {players.map(p => {
                            const isSelected = tradeBlock.find(a => a.id === p.id);
                            return (
                              <div 
                                key={p.id} 
                                className={`roster-player ${isSelected ? 'selected' : ''}`}
                                onClick={() => {
                                  if (isSelected) setTradeBlock(tradeBlock.filter(a => a.id !== p.id));
                                  else setTradeBlock([...tradeBlock, p]);
                                }}
                                style={{padding:'0.4rem 0.5rem', cursor:'pointer'}}
                              >
                                <span>{p.name}</span>
                                <span style={{color: '#888'}}>{p.composite_value}</span>
                              </div>
                            );
                          })}
                        </div>
                      )
                    })}
                  </div>
                )}
                <div style={{marginTop:'0.5rem', fontSize:'0.9rem', color:'#aaa'}}>
                   Assets Selected: <strong>{tradeBlock.length}</strong>
                </div>
             </div>
           )}

           {/* Target Needs */}
           <div style={{flex: 1, minWidth: '300px', display:'flex', flexDirection:'column', gap:'1rem'}}>
              <div>
                 <div className="roster-group-title"><span className="step-num">{searchMode === 'shop' ? '2' : '1'}</span>{searchMode === 'shop' ? 'Target Positions (Optional)' : 'Select Target Position'}</div>
                 <div style={{display:'flex', gap:'0.5rem', flexWrap:'wrap', marginTop:'0.5rem'}}>
                    {['QB', 'RB', 'WR', 'TE', 'Picks'].map(pos => (
                       <button 
                         key={pos} 
                         className={`mode-pill ${targetNeeds.includes(pos) ? 'active contender' : ''}`}
                         onClick={() => {
                            if (targetNeeds.includes(pos)) setTargetNeeds(targetNeeds.filter(p => p !== pos));
                            else setTargetNeeds([...targetNeeds, pos]);
                         }}
                         style={{padding:'0.5rem 1rem'}}
                       >
                         {pos}
                       </button>
                    ))}
                 </div>
                 <div style={{marginTop:'0.5rem', fontSize:'0.85rem', color:'#888'}}>
                    {searchMode === 'shop' ? 'Leave all unselected to search for Best Available Value.' : 'Select the position(s) you want to trade for.'}
                 </div>
              </div>

              {searchMode === 'acquire' && (
                <div>
                   <div className="roster-group-title"><span className="step-num">2</span>Target Value Tier</div>
                   <div style={{display:'flex', gap:'0.5rem', flexWrap:'wrap', marginTop:'0.5rem'}}>
                      {TARGET_TIERS.map(t => (
                         <button
                           key={t.key}
                           className={`mode-pill ${targetTier === t.key ? 'active rebuilder' : ''}`}
                           onClick={() => setTargetTier(t.key)}
                           style={{padding:'0.5rem 1rem'}}
                         >
                           {t.label}
                         </button>
                      ))}
                   </div>
                   <div style={{marginTop:'0.5rem', fontSize:'0.85rem', color:'#888'}}>
                      Depth and Flier tiers are where the fun league-winners hide.
                   </div>
                </div>
              )}

              <div style={{display:'flex', gap:'1rem', marginTop:'auto'}}>
                 {searchMode === 'shop' ? (
                   <>
                     <button className="apply-trade-btn" onClick={() => handleFindTrades('2-way')} disabled={isFinding || tradeBlock.length === 0} style={{background: 'linear-gradient(135deg, #00ff88, #00b3ff)'}}>
                        {isFinding ? 'Crunching...' : 'Find 2-Way Trades'}
                     </button>
                     <button className="apply-trade-btn" onClick={() => handleFindTrades('3-way')} disabled={isFinding || tradeBlock.length < 2} style={{background: 'linear-gradient(135deg, #ff00cc, #ff6600)'}}>
                        {isFinding ? 'Crunching...' : 'Find 3-Way Trades'}
                     </button>
                   </>
                 ) : (
                   <button className="apply-trade-btn" onClick={() => handleFindTrades('inverse')} disabled={isFinding || targetNeeds.length === 0} style={{background: 'linear-gradient(135deg, #ffaa00, #ff0055)', width: '100%'}}>
                      {isFinding ? 'Scanning Roster...' : 'Find Trade Offers'}
                   </button>
                 )}
              </div>
              {searchMode === 'shop' && tradeBlock.length > 4 && (
                <div style={{fontSize:'0.8rem', color:'#ffaa00'}}>
                   ⚠ 3-Way search uses your 4 highest-value selected assets.
                </div>
              )}
           </div>
        </div>

        {/* Results */}
        {finderResults.length > 0 && (
          <div className="ai-suggestions-drawer" style={{marginTop:'2rem'}}>
            <h3 style={{color:'#00ff88', marginBottom:'1rem'}}>Top Combinations Found</h3>
            <div style={{display:'flex', flexDirection:'column', gap:'2rem'}}>
              {finderResults.map((trade, tIdx) => {
                const sentAssets = trade.type === '2-way' ? trade.assetsSent : [...trade.assetsSentToB, ...trade.assetsSentToC];
                const recvAssets = trade.type === '2-way' ? trade.assetsReceived : [...trade.assetsReceivedFromB, ...trade.assetsReceivedFromC];
                const sentTotal = sentAssets.reduce((s, a) => s + (a.composite_value || 0), 0);
                const recvTotal = recvAssets.reduce((s, a) => s + (a.composite_value || 0), 0);
                const net = recvTotal - sentTotal;
                const fairnessPct = (Math.min(trade.ratio, 1 / trade.ratio) * 100).toFixed(1);
                return (
                <div key={tIdx} className="ai-trade-option">
                  <div style={{display:'flex', justifyContent:'space-between', alignItems:'center', marginBottom:'1rem', flexWrap:'wrap', gap:'0.5rem'}}>
                    <h4 style={{margin:0}}>Match #{tIdx + 1} — vs {trade.teamB_name}{trade.type === '3-way' ? ` & ${trade.teamC_name}` : ''}</h4>
                    <div style={{display:'flex', gap:'0.5rem', alignItems:'center'}}>
                      <span style={{background:'rgba(255,255,255,0.1)', padding:'0.2rem 0.6rem', borderRadius:'4px', fontSize:'0.85rem', fontWeight:'bold', color: net >= 0 ? '#00ff88' : '#ff4444'}}>
                         Net: {net >= 0 ? '+' : ''}{net.toLocaleString()}
                      </span>
                      <span style={{background:'rgba(255,255,255,0.1)', padding:'0.2rem 0.6rem', borderRadius:'4px', fontSize:'0.85rem', color: fairnessPct >= 95 ? '#00ff88' : '#ffaa00'}}>
                         Fairness: {fairnessPct}%
                      </span>
                    </div>
                  </div>
                  <div className="ai-trade-framework">

                    {/* User Sends */}
                    <div className="ai-trade-path">
                      <strong style={{color:'#ff4444'}}>You Send:</strong>
                      <ul>
                        {trade.type === '2-way' ? trade.assetsSent.map((a, idx) => (
                          <li key={idx}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> ➔ {trade.teamB_name}</li>
                        )) : (
                          <>
                            {trade.assetsSentToB.map((a, idx) => <li key={`b_${idx}`}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> ➔ {trade.teamB_name}</li>)}
                            {trade.assetsSentToC.map((a, idx) => <li key={`c_${idx}`}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> ➔ {trade.teamC_name}</li>)}
                          </>
                        )}
                      </ul>
                      <div className="trade-path-total">Total: {sentTotal.toLocaleString()}</div>
                    </div>

                    <div className="trade-arrow">⇄</div>

                    {/* User Receives */}
                    <div className="ai-trade-path">
                      <strong style={{color:'#00ff88'}}>You Receive:</strong>
                      <ul>
                         {trade.type === '2-way' ? trade.assetsReceived.map((a, idx) => (
                            <li key={idx}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> (from {trade.teamB_name})</li>
                         )) : (
                           <>
                             {trade.assetsReceivedFromB.map((a, idx) => <li key={`br_${idx}`}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> (from {trade.teamB_name})</li>)}
                             {trade.assetsReceivedFromC.map((a, idx) => <li key={`cr_${idx}`}><PosBadge pos={a.position}/>{a.name} <span className="asset-val">({a.composite_value?.toLocaleString()})</span> (from {trade.teamC_name})</li>)}
                           </>
                         )}
                      </ul>
                      <div className="trade-path-total">Total: {recvTotal.toLocaleString()}</div>
                    </div>

                  </div>

                  {trade.type === '3-way' && trade.broker && (
                    <div style={{marginTop:'0.75rem', fontSize:'0.9rem', color:'#888'}}>
                      🔁 Side deal: <PosBadge pos={trade.broker.asset.position}/>{trade.broker.asset.name} <span className="asset-val">({trade.broker.asset.composite_value?.toLocaleString()})</span> goes from {trade.broker.fromName} to {trade.broker.toName}
                    </div>
                  )}

                  <button className="apply-trade-btn" style={{ marginTop: '1rem' }} onClick={() => applyFinderTrade(trade)}>
                    ⚡ Apply Match to Machine
                  </button>
                </div>
                );
              })}
            </div>
          </div>
        )}
        
        {finderResults.length === 0 && hasSearched && !isFinding && (
          <div style={{color:'#ffaa00', fontStyle:'italic'}}>
            No fair trades found. {searchMode === 'shop' ? 'Try different assets or loosen the target positions.' : 'Try a different position, or your roster may lack the value to buy at this position.'}
          </div>
        )}
        {finderResults.length === 0 && !hasSearched && tradeBlock.length > 0 && !isFinding && (
          <div style={{color:'#888', fontStyle:'italic'}}>Click generate to find trades for these assets...</div>
        )}
      </div>

      {/* Trade Panels Grid */}
      <div className={`trade-grid ${isThreeWay ? 'three-way' : 'two-way'}`}>
        {renderPanel("Side A", teamA, setTeamA, modeA, setModeA, destA, setDestA, assetsA)}
        {renderPanel("Side B", teamB, setTeamB, modeB, setModeB, destB, setDestB, assetsB)}
        {isThreeWay && renderPanel("Side C", teamC, setTeamC, modeC, setModeC, destC, setDestC, assetsC)}
      </div>

      <button className="eval-btn" onClick={() => calculateTrade()} disabled={isEvaluating || !teamA || !teamB}>
        {isEvaluating ? 'Crunching Numbers...' : '⚡ Evaluate Trade'}
      </button>

      {/* Evaluation Results */}
      {evaluation && (
        <div className="glass-panel results-panel">
          {evaluation.isThreeWay ? (
            <div>
              <h2 className="verdict fair">3-Way Impact</h2>
              <div className="three-way-results">
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamA))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netA >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netA > 0 ? '+' : ''}{Math.round(evaluation.netA)}
                  </div>
                </div>
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamB))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netB >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netB > 0 ? '+' : ''}{Math.round(evaluation.netB)}
                  </div>
                </div>
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamC))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netC >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netC > 0 ? '+' : ''}{Math.round(evaluation.netC)}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div>
              <h2 className={`verdict ${evaluation.winner === 'sideA' ? 'win' : evaluation.winner === 'sideB' ? 'lose' : 'fair'}`}>
                {evaluation.margin_description}
              </h2>
              <div className="fairness-bar">
                <div className="fairness-fill" style={{width: `${(evaluation.final_sideA_total / (evaluation.final_sideA_total + evaluation.final_sideB_total) * 100) || 50}%`}} />
                <div className="fairness-marker" />
              </div>
              <div style={{display:'flex', justifyContent:'space-between', color:'#888', fontWeight:'bold', marginTop:'1rem'}}>
                <span>Side A: {evaluation.final_sideA_total}</span>
                <span>Side B: {evaluation.final_sideB_total}</span>
              </div>

              {balanceSuggestion && (
                <div className="balance-suggestion glass-panel" style={{ marginTop: '1.5rem', border: '1px dashed #00ff88', background: 'rgba(0, 255, 136, 0.05)', padding: '1.5rem', borderRadius: '12px', textAlign: 'left' }}>
                  <p style={{ margin: 0, color: '#ddd', fontSize: '1rem', lineHeight: '1.5' }}>
                    ⚖️ <strong>Auto-Balance Suggestion</strong>: Add <strong>{balanceSuggestion.player.name}</strong> (Value: {balanceSuggestion.player.composite_value}) from <strong>{balanceSuggestion.sourceTeamName}</strong> to balance this trade.
                  </p>
                  <button className="apply-balance-btn" onClick={applyBalance} style={{ marginTop: '0.75rem', background: '#00ff88', color: '#000', border: 'none', padding: '0.6rem 1.2rem', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s', fontSize: '0.95rem' }}>
                    Add {balanceSuggestion.player.name}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      )}

    </div>
  );
}
