import { useState, useEffect, useRef, useMemo } from 'react';
import { GoogleGenerativeAI } from '@google/generative-ai';
import './TradeMachine.css';

const MODES = ['contender', 'neutral', 'rebuilder'];
const API_BASE = import.meta.env.VITE_API_BASE || 'http://localhost:5000'; // Dynasty Evaluator Backend

export default function TradeMachine() {
  const [leagues, setLeagues] = useState([]);
  const [config, setConfig] = useState(null);
  const [selectedLeagueId, setSelectedLeagueId] = useState('');
  
  const [isThreeWay, setIsThreeWay] = useState(false);
  const [rankingsMap, setRankingsMap] = useState(new Map());
  const [rosterData, setRosterData] = useState([]); // List of team objects
  const [isLoadingLeague, setIsLoadingLeague] = useState(false);
  
  // Selected teams for the trade panels (Team A, Team B, Team C)
  const [teamA, setTeamA] = useState('');
  const [teamB, setTeamB] = useState('');
  const [teamC, setTeamC] = useState('');

  // Roster modes
  const [modeA, setModeA] = useState('neutral');
  const [modeB, setModeB] = useState('neutral');
  const [modeC, setModeC] = useState('neutral');

  // Trade Assets (Array of { id, originalOwner, dest })
  const [assetsA, setAssetsA] = useState([]);
  const [assetsB, setAssetsB] = useState([]);
  const [assetsC, setAssetsC] = useState([]);

  // AI Assistant State
  const [aiQuery, setAiQuery] = useState('');
  const [isAiLoading, setIsAiLoading] = useState(false);
  const [aiSuggestion, setAiSuggestion] = useState('');
  const [parsedAiSuggestion, setParsedAiSuggestion] = useState(null);
  
  // Evaluation Result
  const [evaluation, setEvaluation] = useState(null);
  const [isEvaluating, setIsEvaluating] = useState(false);

  // 1. Initial Load: Configs & Rankings
  useEffect(() => {
    async function init() {
      try {
        // Fetch configs generated by background script
        const [lgRes, cfgRes, rankRes] = await Promise.all([
          fetch('/leagues.json').catch(() => null),
          fetch('/config.json').catch(() => null),
          fetch(`${API_BASE}/api/rankings`).catch(() => null)
        ]);

        if (lgRes && lgRes.ok) setLeagues(await lgRes.json());
        if (cfgRes && cfgRes.ok) setConfig(await cfgRes.json());
        
        if (rankRes && rankRes.ok) {
          const rList = await rankRes.json();
          const rMap = new Map();
          rList.forEach(p => {
            if (p.sleeper_id) rMap.set(p.sleeper_id, p);
            // Also map by name and KTC ID for draft picks
            rMap.set(p.name, p);
          });
          setRankingsMap(rMap);
        }
      } catch (err) {
        console.error("Initialization error:", err);
      }
    }
    init();
  }, []);

  // 2. Load Sleeper League Rosters
  useEffect(() => {
    if (!selectedLeagueId) return;
    
    async function fetchLeague() {
      setIsLoadingLeague(true);
      try {
        const [uRes, rRes] = await Promise.all([
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/users`),
          fetch(`https://api.sleeper.app/v1/league/${selectedLeagueId}/rosters`)
        ]);
        
        const users = await uRes.json();
        const rosters = await rRes.json();
        
        const formatted = rosters.map(r => {
          const user = users.find(u => u.user_id === r.owner_id);
          const name = user?.display_name || `Team ${r.roster_id}`;
          
          // Group players by position
          const players = { QB: [], RB: [], WR: [], TE: [], Picks: [] };
          if (r.players) {
            r.players.forEach(pid => {
              const p = rankingsMap.get(pid);
              if (p && players[p.position]) {
                players[p.position].push(p);
              }
            });
          }
          // Sort each position group
          Object.keys(players).forEach(pos => {
            players[pos].sort((a, b) => b.composite_value - a.composite_value);
          });

          return { roster_id: r.roster_id, name, players };
        });

        setRosterData(formatted);
        // Reset selections
        setTeamA(''); setTeamB(''); setTeamC('');
        setAssetsA([]); setAssetsB([]); setAssetsC([]);
        setEvaluation(null);
      } catch (err) {
        console.error("Failed to load Sleeper data", err);
      } finally {
        setIsLoadingLeague(false);
      }
    }
    fetchLeague();
  }, [selectedLeagueId, rankingsMap]);

  // 3. AI Assistant
  const handleAiSearch = async () => {
    if (!aiQuery) return;
    if (!config?.gemini_api_key || config.gemini_api_key.includes("YOUR_GEMINI_API_KEY") || config.gemini_api_key === '') {
      setAiSuggestion("Error: Gemini API Key is missing. Please set a valid `gemini_api_key` in config.json.");
      return;
    }
    
    setIsAiLoading(true);
    setAiSuggestion('');
    setParsedAiSuggestion(null);

    try {
      const genAI = new GoogleGenerativeAI(config.gemini_api_key);

      // Find user's manager name in the current active league
      const activeLeague = leagues.find(l => String(l.sleeper_league_id) === String(selectedLeagueId));
      const userManagerName = activeLeague?.user_team_username || config?.user_team_username || '';

      const context = rosterData.map(t => {
        const qbs = t.players.QB.map(p => `${p.name} (Age: ${p.age}, Value: ${p.composite_value})`).join(', ');
        const rbs = t.players.RB.map(p => `${p.name} (Age: ${p.age}, Value: ${p.composite_value})`).join(', ');
        const wrs = t.players.WR.map(p => `${p.name} (Age: ${p.age}, Value: ${p.composite_value})`).join(', ');
        const tes = t.players.TE.map(p => `${p.name} (Age: ${p.age}, Value: ${p.composite_value})`).join(', ');
        return `Manager Name: "${t.name}" (Roster ID: ${t.roster_id})
- QBs: ${qbs || 'None'}
- RBs: ${rbs || 'None'}
- WRs: ${wrs || 'None'}
- TEs: ${tes || 'None'}`;
      }).join('\n\n');

      const prompt = `You are a personal fantasy football AI trade assistant exclusively for the manager: "${userManagerName}". 
User Request: "${aiQuery}"
When the user uses first-person pronouns like "I", "me", "my team", "my roster", "my picks", "who should I trade", they are referring to this manager.

League Teams & Roster Lists (contains player age and dynasty values from our rankings database):
${context}

Instructions:
1. ONLY SUGGEST TRADES FOR THE USER:
   - EVERY trade you suggest MUST include the user ("${userManagerName}") as one of the primary trading partners (e.g. as Team A). Do NOT suggest trades between two other teams.
   - Target Teams: If the user requests to trade with a specific manager, focus on finding deals with that manager.
   - Sell Candidates/Buy Targets: Follow user directions to trade away or acquire specific players.

2. BUILD SMART, MATHEMATICALLY BALANCED WIN-WIN TRADES:
   - ALWAYS look at the "Value" field for each player. These are active dynasty player values from our database.
   - A standard fair trade means the total value sent by Team A should be roughly equal to the total value sent by Team B (within 10-15% difference).
   - Do not propose highly lopsided trades unless the user explicitly requests to "fleece" or steal a player.
   - Identify positional surpluses and deficits (e.g., a team with 5 QBs has a surplus; a team with 1 QB has a deficit) to find the perfect trade partner.

3. PROVIDE MULTIPLE OPTIONS & DEEP ANALYSIS:
   - Provide exactly 3 different trade options for the user. These could be with different teams or different packages with the same team.
   - For each trade, provide a deep, multi-faceted explanation ("rationale"). Explain why it makes sense strategically for BOTH sides, highlighting the database values, age profiles, and positional needs. Don't just say "it's fair", explain the dynasty implications.

4. STRICT CONSTRAINTS:
   - Do not invent players. Every player in the trade must exist on the respective roster in the list above.
   - Do not confuse Manager Names with Player Names.
   - Maintain the manager names exactly as written in the list.

5. RESPONSE FORMAT:
   You must return your response ONLY as a JSON object matching this schema:
   {
     "trades": [
       {
         "teamA_name": "Name of Manager/Team A (Must be ${userManagerName})",
         "teamB_name": "Name of Manager/Team B (Must match the list exactly)",
         "teamC_name": "Name of Manager/Team C (Must match the list exactly, or null if it's a 2-way trade)",
         "isThreeWay": false,
         "assetsA_sent": [
           { "name": "Player Name", "dest_team_name": "Name of Manager receiving this player" }
         ],
         "assetsB_sent": [
           { "name": "Player Name", "dest_team_name": "Name of Manager receiving this player" }
         ],
         "assetsC_sent": [
           { "name": "Player Name", "dest_team_name": "Name of Manager receiving this player" }
         ],
         "rationale": "A detailed, insightful explanation of why this trade makes strategic sense for all sides, referencing specific player values, age dynamics, and roster needs."
       }
     ]
   }
   Return ONLY the JSON object.`;

      let result;
      try {
        console.log("Attempting generation with gemini-2.5-flash...");
        const model = genAI.getGenerativeModel({ 
          model: "gemini-2.5-flash",
          generationConfig: { responseMimeType: "application/json" }
        });
        result = await model.generateContent(prompt);
      } catch (firstErr) {
        console.warn("Flash model failed (possibly 503). Retrying with gemini-2.5-pro...", firstErr);
        const model = genAI.getGenerativeModel({ 
          model: "gemini-2.5-pro",
          generationConfig: { responseMimeType: "application/json" }
        });
        result = await model.generateContent(prompt);
      }

      const text = result.response.text();
      try {
        const parsed = JSON.parse(text);
        setParsedAiSuggestion(parsed);
      } catch (jsonErr) {
        console.error("Failed to parse AI JSON:", jsonErr);
        setAiSuggestion(text);
      }
    } catch (err) {
      console.error(err);
      const errMsg = err?.message || '';
      if (errMsg.includes('429') || errMsg.toLowerCase().includes('quota') || errMsg.includes('RESOURCE_EXHAUSTED')) {
        setAiSuggestion("Error: Gemini API key has exceeded its free tier quota (429 Rate/Quota Limit reached). Please try again in a few minutes, or check if the background scripts are running too frequently.");
      } else {
        setAiSuggestion(`Error: Failed to fetch AI suggestion. (${errMsg || 'Unknown error'})`);
      }
    } finally {
      setIsAiLoading(false);
    }
  };

  const applyAiTrade = (tradeObj) => {
    if (!tradeObj) return;

    // Find the teams involved
    const tA = rosterData.find(t => t.name.toLowerCase() === tradeObj.teamA_name.toLowerCase());
    const tB = rosterData.find(t => t.name.toLowerCase() === tradeObj.teamB_name.toLowerCase());
    const tC = tradeObj.isThreeWay && tradeObj.teamC_name
      ? rosterData.find(t => t.name.toLowerCase() === tradeObj.teamC_name.toLowerCase())
      : null;

    if (!tA || !tB) {
      alert(`Could not find matching teams in this league. AI suggested: "${tradeObj.teamA_name}" and "${tradeObj.teamB_name}".`);
      return;
    }

    // Set active teams
    setTeamA(String(tA.roster_id));
    setTeamB(String(tB.roster_id));
    if (tC) {
      setIsThreeWay(true);
      setTeamC(String(tC.roster_id));
    } else {
      setIsThreeWay(false);
      setTeamC('');
    }

    // Look up assets
    const resolveAssets = (assetsSent, sourceTeamId) => {
      const resolved = [];
      assetsSent.forEach(a => {
        // Find player by name in rankingsMap
        let player = rankingsMap.get(a.name);
        
        // If not found, do a case-insensitive name lookup across all rankingsMap keys
        if (!player) {
          for (let [nameKey, p] of rankingsMap.entries()) {
            if (nameKey.toLowerCase() === a.name.toLowerCase()) {
              player = p;
              break;
            }
          }
        }

        // If still not found, search in the source team's actual roster
        if (!player) {
          const sourceTeam = rosterData.find(t => String(t.roster_id) === String(sourceTeamId));
          if (sourceTeam) {
            const allPlayers = [
              ...(sourceTeam.players.QB || []),
              ...(sourceTeam.players.RB || []),
              ...(sourceTeam.players.WR || []),
              ...(sourceTeam.players.TE || [])
            ];
            player = allPlayers.find(p => p.name.toLowerCase().includes(a.name.toLowerCase()));
          }
        }

        if (player) {
          // Find destId
          const destTeam = rosterData.find(t => t.name.toLowerCase() === a.dest_team_name.toLowerCase());
          resolved.push({
            ...player,
            destId: destTeam ? String(destTeam.roster_id) : String(sourceTeamId === tA.roster_id ? tB.roster_id : tA.roster_id)
          });
        }
      });
      return resolved;
    };

    const resolvedA = resolveAssets(tradeObj.assetsA_sent, tA.roster_id);
    const resolvedB = resolveAssets(tradeObj.assetsB_sent, tB.roster_id);
    const resolvedC = tC ? resolveAssets(tradeObj.assetsC_sent, tC.roster_id) : [];

    setAssetsA(resolvedA);
    setAssetsB(resolvedB);
    if (tC) {
      setAssetsC(resolvedC);
    } else {
      setAssetsC([]);
    }

    // Trigger evaluation automatically!
    calculateTrade(
      resolvedA,
      resolvedB,
      resolvedC,
      !!tC,
      String(tA.roster_id),
      String(tB.roster_id),
      tC ? String(tC.roster_id) : ''
    );
  };

  const balanceSuggestion = useMemo(() => {
    if (!evaluation || evaluation.isThreeWay || !teamA || !teamB) return null;
    
    const valA = evaluation.final_sideA_total || 0;
    const valB = evaluation.final_sideB_total || 0;
    const diff = Math.abs(valA - valB);
    
    // If the difference is minor (less than 50), the trade is already perfectly balanced
    if (diff < 50) return null;

    // If valA > valB: Side A total sent is greater than Side B total sent.
    // That means Side A is sending more value. Side B is winning.
    // To balance: Side B needs to add a player to send to Side A.
    // If valB > valA: Side B is sending more value. Side A is winning.
    // To balance: Side A needs to add a player to send to Side B.
    const winningId = valA > valB ? teamB : teamA; // The team receiving more value (gets more, sends less)
    const losingId = valA > valB ? teamA : teamB;  // The team receiving less value (sends more, gets less)
    
    const winningRoster = rosterData.find(t => String(t.roster_id) === String(winningId));
    if (!winningRoster) return null;
    
    const winningAssets = winningId === teamA ? assetsA : winningId === teamB ? assetsB : assetsC;
    
    // Gather all players on the winning manager's roster not currently in the trade
    const candidatePlayers = [
      ...winningRoster.players.QB,
      ...winningRoster.players.RB,
      ...winningRoster.players.WR,
      ...winningRoster.players.TE
    ].filter(p => !winningAssets.some(a => a.id === p.id));
    
    // Find the player whose value is closest to the difference
    let bestPlayer = null;
    let minDiff = Infinity;
    
    candidatePlayers.forEach(p => {
      const d = Math.abs(p.composite_value - diff);
      if (d < minDiff) {
        minDiff = d;
        bestPlayer = p;
      }
    });
    
    if (bestPlayer && bestPlayer.composite_value > 0) {
      return {
        player: bestPlayer,
        sourceTeamId: winningId,
        destTeamId: losingId,
        sourceTeamName: winningRoster.name,
        targetTeamName: rosterData.find(t => String(t.roster_id) === String(losingId))?.name || 'the other side'
      };
    }
    
    return null;
  }, [evaluation, teamA, teamB, assetsA, assetsB, rosterData]);

  const applyBalance = () => {
    if (!balanceSuggestion) return;
    const { sourceTeamId, player, destTeamId } = balanceSuggestion;
    
    const listMap = { [teamA]: setAssetsA, [teamB]: setAssetsB, [teamC]: setAssetsC };
    const curMap = { [teamA]: assetsA, [teamB]: assetsB, [teamC]: assetsC };
    
    const curList = curMap[sourceTeamId];
    const setList = listMap[sourceTeamId];
    if (setList) {
      const updatedAsset = { ...player, destId: destTeamId };
      const updatedList = [...curList, updatedAsset];
      setList(updatedList);
      
      const nextA = sourceTeamId === teamA ? updatedList : assetsA;
      const nextB = sourceTeamId === teamB ? updatedList : assetsB;
      const nextC = sourceTeamId === teamC ? updatedList : assetsC;
      
      calculateTrade(nextA, nextB, nextC, isThreeWay, teamA, teamB, teamC);
    }
  };

  // 4. Trade Asset Selection & Evaluation
  const toggleAsset = (teamId, asset, destId) => {
    const listMap = { [teamA]: setAssetsA, [teamB]: setAssetsB, [teamC]: setAssetsC };
    const curMap = { [teamA]: assetsA, [teamB]: assetsB, [teamC]: assetsC };
    
    const curList = curMap[teamId];
    const setList = listMap[teamId];
    if (!setList) return;

    if (curList.find(a => a.id === asset.id)) {
      setList(curList.filter(a => a.id !== asset.id));
    } else {
      setList([...curList, { ...asset, destId }]);
    }
  };

  const calculateTrade = async (
    overrideA,
    overrideB,
    overrideC,
    forceThreeWay,
    overrideTeamA,
    overrideTeamB,
    overrideTeamC
  ) => {
    const finalA = overrideA || assetsA;
    const finalB = overrideB || assetsB;
    const finalC = overrideC || assetsC;
    const finalThreeWay = forceThreeWay !== undefined ? forceThreeWay : isThreeWay;
    const finalTeamA = overrideTeamA || teamA;
    const finalTeamB = overrideTeamB || teamB;
    const finalTeamC = overrideTeamC || teamC;

    setIsEvaluating(true);
    try {
      if (!finalThreeWay) {
        // Standard 2-way call to evaluator
        const res = await fetch(`${API_BASE}/api/evaluate`, {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({
            sideA: { players: finalA.map(a => a.id), picks: [] },
            sideB: { players: finalB.map(a => a.id), picks: [] },
            settings: { team_1_mode: modeA, team_2_mode: modeB }
          })
        });
        const data = await res.json();
        setEvaluation(data);
      } else {
        // 3-way offline calculation
        const getAdjusted = (asset, mode) => {
           if (mode === 'contender') return asset.composite_value * (asset.age > 27 ? 1.1 : 0.95);
           if (mode === 'rebuilder') return asset.composite_value * (asset.age < 24 ? 1.15 : 0.8);
           return asset.composite_value;
        };

        const calcNet = (teamId, sentAssets, mode) => {
          let sentValue = sentAssets.reduce((s, a) => s + getAdjusted(a, mode), 0);
          let receivedValue = 0;
          [finalA, finalB, finalC].forEach(list => {
            list.forEach(a => {
              if (a.destId === teamId) receivedValue += getAdjusted(a, mode);
            });
          });
          return receivedValue - sentValue;
        };

        const netA = calcNet(finalTeamA, finalA, modeA);
        const netB = calcNet(finalTeamB, finalB, modeB);
        const netC = calcNet(finalTeamC, finalC, modeC);
        
        setEvaluation({ isThreeWay: true, netA, netB, netC });
      }
    } catch (err) {
      console.error(err);
    } finally {
      setIsEvaluating(false);
    }
  };

  const renderRoster = (teamId, currentDest) => {
    const team = rosterData.find(t => String(t.roster_id) === String(teamId));
    if (!team) return <div style={{opacity:0.5, padding:'1rem'}}>Select a team</div>;
    
    // which assets has this team already added?
    const teamAssets = teamId === teamA ? assetsA : teamId === teamB ? assetsB : assetsC;

    return (
      <div className="roster-picker">
        {['QB', 'RB', 'WR', 'TE'].map(pos => {
          const players = team.players[pos];
          if (!players || players.length === 0) return null;
          return (
            <div key={pos} className="roster-group">
              <div className="roster-group-title">{pos}</div>
              {players.map(p => {
                const isSelected = teamAssets.find(a => a.id === p.id);
                return (
                  <div 
                    key={p.id} 
                    className={`roster-player ${isSelected ? 'selected' : ''}`}
                    onClick={() => toggleAsset(teamId, p, currentDest)}
                  >
                    <span>{p.name}</span>
                    <span style={{color: '#888'}}>{p.composite_value}</span>
                  </div>
                );
              })}
            </div>
          )
        })}
      </div>
    );
  };

  const renderPanel = (sideLabel, teamState, setTeam, modeState, setMode, destState, setDest, assetsList) => (
    <div className="team-panel glass-panel">
      <div className="team-header">
        <h3>{sideLabel}</h3>
        <select className="team-select" value={teamState} onChange={e => setTeam(e.target.value)}>
          <option value="">-- Select Team --</option>
          {rosterData.map(t => <option key={t.roster_id} value={t.roster_id}>{t.name}</option>)}
        </select>
      </div>
      
      <div className="mode-pills">
        {MODES.map(m => (
          <button key={m} className={`mode-pill ${modeState === m ? `active ${m}` : ''}`} onClick={() => setMode(m)}>
            {m}
          </button>
        ))}
      </div>

      <div className="assets-box" style={{marginTop:'1rem'}}>
        <div className="roster-group-title">Assets Sent</div>
        {assetsList.length === 0 && <div style={{opacity:0.5, fontSize:'0.9rem', padding:'0.5rem'}}>No assets selected</div>}
        {assetsList.map(a => (
          <div key={a.id} className="asset-item">
            <div className="asset-info">
              <span className="asset-name">{a.name}</span>
              <span className="asset-dest">
                To: {rosterData.find(t=>String(t.roster_id)===String(a.destId))?.name || 'Unknown'}
              </span>
            </div>
            <div className="asset-actions">
              <button onClick={() => toggleAsset(teamState, a, a.destId)}>✖</button>
            </div>
          </div>
        ))}
      </div>

      {teamState && (
        <div style={{marginTop:'1rem'}}>
          <div style={{display:'flex', gap:'0.5rem', marginBottom:'0.5rem'}}>
            <span className="roster-group-title" style={{border:'none', margin:0}}>Send to:</span>
            <select style={{background:'rgba(0,0,0,0.5)', color:'white', border:'1px solid #555', borderRadius:'4px'}} value={destState} onChange={e => setDest(e.target.value)}>
              <option value="">Select Dest</option>
              {teamState !== teamA && teamA && <option value={teamA}>Side A</option>}
              {teamState !== teamB && teamB && <option value={teamB}>Side B</option>}
              {isThreeWay && teamState !== teamC && teamC && <option value={teamC}>Side C</option>}
            </select>
          </div>
          {renderRoster(teamState, destState)}
        </div>
      )}
    </div>
  );

  // Default dests
  const [destA, setDestA] = useState(teamB);
  const [destB, setDestB] = useState(teamA);
  const [destC, setDestC] = useState(teamA);

  // Sync default dests when teams change
  useEffect(() => { if (!destA) setDestA(teamB); }, [teamB]);
  useEffect(() => { if (!destB) setDestB(teamA); }, [teamA]);
  useEffect(() => { if (!destC) setDestC(teamA); }, [teamA]);

  return (
    <div className="trade-machine-wrapper">
      
      {/* Top Controls */}
      <div className="glass-panel trade-controls">
        <div className="league-selector">
          <span>🏈 League:</span>
          <select value={selectedLeagueId} onChange={(e) => setSelectedLeagueId(e.target.value)}>
            <option value="">-- Select League --</option>
            {leagues.map(l => (
              <option key={l.sleeper_league_id} value={l.sleeper_league_id}>{l.name}</option>
            ))}
          </select>
          {isLoadingLeague && <span style={{color: '#00ff88'}}>Loading rosters...</span>}
        </div>

        <div className="trade-type-toggle">
          <button className={!isThreeWay ? 'active' : ''} onClick={() => {setIsThreeWay(false); setTeamC(''); setAssetsC([]);}}>2-Way Trade</button>
          <button className={isThreeWay ? 'active' : ''} onClick={() => setIsThreeWay(true)}>3-Way Trade</button>
        </div>
      </div>

      {/* AI Assistant */}
      <div className="glass-panel ai-assistant-container">
        <div className="ai-search-bar">
          <input 
            type="text" 
            placeholder="Ask the AI Trade Assistant (e.g. 'Find me a deal to sell McCaffrey for picks...')"
            value={aiQuery}
            onChange={e => setAiQuery(e.target.value)}
            onKeyDown={e => e.key === 'Enter' && handleAiSearch()}
          />
          <button onClick={handleAiSearch} disabled={isAiLoading || !aiQuery}>
            {isAiLoading ? 'Thinking...' : '✨ Generate'}
          </button>
        </div>
        {parsedAiSuggestion?.trades ? (
          <div className="ai-suggestions-drawer">
            <h3 style={{color:'#00ff88', marginBottom:'1rem'}}>AI Trade Suggestions</h3>
            <div style={{display:'flex', flexDirection:'column', gap:'2rem'}}>
              {parsedAiSuggestion.trades.map((trade, tIdx) => (
                <div key={tIdx} className="ai-trade-option" style={{ background: 'rgba(0,0,0,0.3)', padding: '1.5rem', borderRadius: '12px', border: '1px solid #333' }}>
                  <h4 style={{marginTop:0, marginBottom:'1rem', color:'#fff'}}>Option {tIdx + 1}</h4>
                  <div className="ai-trade-framework">
                    <div className="ai-trade-path">
                      <strong>{trade.teamA_name} sends:</strong>
                      {trade.assetsA_sent.length === 0 ? (
                        <div style={{opacity:0.5, fontSize:'0.9rem'}}>No players</div>
                      ) : (
                        <ul>
                          {trade.assetsA_sent.map((a, idx) => (
                            <li key={idx}>{a.name} ➔ {a.dest_team_name}</li>
                          ))}
                        </ul>
                      )}
                    </div>
                    
                    <div className="ai-trade-path">
                      <strong>{trade.teamB_name} sends:</strong>
                      {trade.assetsB_sent.length === 0 ? (
                        <div style={{opacity:0.5, fontSize:'0.9rem'}}>No players</div>
                      ) : (
                        <ul>
                          {trade.assetsB_sent.map((a, idx) => (
                            <li key={idx}>{a.name} ➔ {a.dest_team_name}</li>
                          ))}
                        </ul>
                      )}
                    </div>

                    {trade.isThreeWay && trade.teamC_name && (
                      <div className="ai-trade-path">
                        <strong>{trade.teamC_name} sends:</strong>
                        {trade.assetsC_sent.length === 0 ? (
                          <div style={{opacity:0.5, fontSize:'0.9rem'}}>No players</div>
                        ) : (
                          <ul>
                            {trade.assetsC_sent.map((a, idx) => (
                              <li key={idx}>{a.name} ➔ {a.dest_team_name}</li>
                            ))}
                          </ul>
                        )}
                      </div>
                    )}
                  </div>

                  <div className="ai-rationale" style={{ marginTop: '1rem', fontStyle: 'italic', color: '#ccc', lineHeight: '1.6' }}>
                    <strong>Rationale: </strong>{trade.rationale}
                  </div>

                  <button className="apply-trade-btn" style={{ marginTop: '1rem' }} onClick={() => applyAiTrade(trade)}>
                    ⚡ Apply Option {tIdx + 1} to Machine
                  </button>
                </div>
              ))}
            </div>
          </div>
        ) : aiSuggestion ? (
          <div className="ai-suggestions-drawer">
            <h3 style={{color:'#00ff88', marginBottom:'0.5rem'}}>AI Suggestion</h3>
            <div style={{lineHeight:'1.6', color:'#ddd'}}>{aiSuggestion}</div>
          </div>
        ) : null}
      </div>

      {/* Trade Panels Grid */}
      <div className={`trade-grid ${isThreeWay ? 'three-way' : 'two-way'}`}>
        {renderPanel("Side A", teamA, setTeamA, modeA, setModeA, destA, setDestA, assetsA)}
        {renderPanel("Side B", teamB, setTeamB, modeB, setModeB, destB, setDestB, assetsB)}
        {isThreeWay && renderPanel("Side C", teamC, setTeamC, modeC, setModeC, destC, setDestC, assetsC)}
      </div>

      <button className="eval-btn" onClick={calculateTrade} disabled={isEvaluating || !teamA || !teamB}>
        {isEvaluating ? 'Crunching Numbers...' : '⚡ Evaluate Trade'}
      </button>

      {/* Evaluation Results */}
      {evaluation && (
        <div className="glass-panel results-panel">
          {evaluation.isThreeWay ? (
            <div>
              <h2 className="verdict fair">3-Way Impact</h2>
              <div className="three-way-results">
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamA))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netA >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netA > 0 ? '+' : ''}{Math.round(evaluation.netA)}
                  </div>
                </div>
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamB))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netB >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netB > 0 ? '+' : ''}{Math.round(evaluation.netB)}
                  </div>
                </div>
                <div className="net-card">
                  <h4>{rosterData.find(t=>String(t.roster_id)===String(teamC))?.name} Net</h4>
                  <div className={`net-value ${evaluation.netC >= 0 ? 'positive' : 'negative'}`}>
                    {evaluation.netC > 0 ? '+' : ''}{Math.round(evaluation.netC)}
                  </div>
                </div>
              </div>
            </div>
          ) : (
            <div>
              <h2 className={`verdict ${evaluation.winner === 'sideA' ? 'win' : evaluation.winner === 'sideB' ? 'lose' : 'fair'}`}>
                {evaluation.margin_description}
              </h2>
              <div className="fairness-bar">
                <div className="fairness-fill" style={{width: `${(evaluation.final_sideA_total / (evaluation.final_sideA_total + evaluation.final_sideB_total) * 100) || 50}%`}} />
                <div className="fairness-marker" />
              </div>
              <div style={{display:'flex', justifyContent:'space-between', color:'#888', fontWeight:'bold', marginTop:'1rem'}}>
                <span>Side A: {evaluation.final_sideA_total}</span>
                <span>Side B: {evaluation.final_sideB_total}</span>
              </div>

              {balanceSuggestion && (
                <div className="balance-suggestion glass-panel" style={{ marginTop: '1.5rem', border: '1px dashed #00ff88', background: 'rgba(0, 255, 136, 0.05)', padding: '1.5rem', borderRadius: '12px', textAlign: 'left' }}>
                  <p style={{ margin: 0, color: '#ddd', fontSize: '1rem', lineHeight: '1.5' }}>
                    ⚖️ **Auto-Balance Suggestion**: Add **{balanceSuggestion.player.name}** (Value: {balanceSuggestion.player.composite_value}) from **{balanceSuggestion.sourceTeamName}** to balance this trade.
                  </p>
                  <button className="apply-balance-btn" onClick={applyBalance} style={{ marginTop: '0.75rem', background: '#00ff88', color: '#000', border: 'none', padding: '0.6rem 1.2rem', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', transition: 'all 0.2s', fontSize: '0.95rem' }}>
                    Add {balanceSuggestion.player.name}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      )}

    </div>
  );
}
